const { contextBridge, ipcRenderer } = require('electron');
const callbacks = { created: [], exit: [], cwd: [], busy: [], data: [], sessions: [], settings: [], extensions: [], ask: [], windowFocused: [], hotkeySummoned: [], menu: [], canvas: [] };
// Drawings per terminal, pushed by the test over test:canvas as the deck-canvas skill would post them.
const canvasFrames = {};
ipcRenderer.on('test:canvas', (_event, termId, frame) => { const frames = canvasFrames[termId] ?? []; const existing = frames.find(f => f.title.trim().toLowerCase() === frame.title.trim().toLowerCase()); canvasFrames[termId] = existing ? frames.map(f => f === existing ? { ...frame, id: existing.id, title: existing.title, createdAt: existing.createdAt } : f) : [...frames, frame]; callbacks.canvas.forEach(cb => cb(termId, canvasFrames[termId])); });
const worktree = (repo, branch, dirtyFiles, size, merged) => ({ path: `/Users/demo/www/.worktrees/${branch}`, repo, repoRoot: `/Users/demo/www/${repo}`, branch, dirtyFiles, size, merged });
const worktrees = [
  worktree('api', 'INI-1-feature', 0, 2.5 * 1024 ** 3, true),
  worktree('web', 'INI-2-wip', 3, 900 * 1024 ** 2, false),
  worktree('api', 'INI-3-done', 0, 1.2 * 1024 ** 3, true),
];
const removedWorktrees = [];
const sessionPr = (number, state) => ({ repo:'demo/api', number, title:'PR '+number, state, isDraft:false, url:'https://example.test/pull/'+number, author:'me', updatedAt:new Date().toISOString() });
const sessionPrs = { 'claude-swept': [sessionPr(21, 'MERGED')], 'claude-swept-too': [sessionPr(23, 'MERGED')], 'codex:kept': [sessionPr(22, 'OPEN')] };
const issue = (key, summary, statusId, statusName, assignee, hours, type) => ({ id:'i'+key, key, summary, type, statusId, statusName, assignee, assigneeId:assignee==='Me'?'me':assignee, updated:new Date(Date.now()-hours*3600e3).toISOString(), url:'https://example.test/'+key });
const boardCache = { provider:'jira', boardName:'Deck · Sprint 14', myAccountId:'me', at:Date.now(), columns:[{name:'To do',statusIds:['1']},{name:'In progress',statusIds:['2']},{name:'In review',statusIds:['3']},{name:'Done',statusIds:['4']}], issues:[
  issue('DECK-147','Linear adapter: map cycles to board columns','1','To Do','Me',30,'Story'),
  issue('DECK-151','Quake panel should remember its height per display','1','To Do',null,52,'Task'),
  issue('DECK-152','Board cards show the agent that touched them','1','To Do','Sam Okafor',74,'Task'),
  issue('DECK-131','First-run setup for the summon hotkey','2','In Progress','Me',1,'Story'),
  issue('DECK-138','Index archived Codex sessions for search','2','In Progress','Ada Meyer',5,'Task'),
  issue('DECK-126','Move sessions into their own table','3','In Review','Me',2,'Story'),
  issue('DECK-129','Start a fix agent when CI fails on my PR','3','In Review','Sam Okafor',9,'Story'),
  issue('DECK-144','Pull request diff: collapse resolved threads','3','In Review','Ada Meyer',26,'Bug'),
  issue('DECK-118','Search palette over every past conversation','4','Done','Me',28,'Story'),
  issue('DECK-121','Keyboard flow for the review queue','4','Done','Sam Okafor',49,'Task'),
] };
const pr = (number, extra) => ({ repo:'demo/api', number, title:'PR '+number, url:'https://example.test/'+number, author:'me', isDraft:false, updatedAt:new Date().toISOString(), headRefName:'f', baseRefName:'main', reviewDecision:null, mergeable:'MERGEABLE', checks:'SUCCESS', ...extra });
const reviewed = [];
const demoAnswer = 'Two of your PRs need attention.\n\n- **#12 Retry uploads on timeout** — CI failing on `test:pty`. Ready to start a fix agent in `~/www/api`.\n- **#13 Add dark theme** — green, waiting on review from teammate.\n\nSay *fix #12* and I will open a Codex session on it.';
const demo = process.argv.includes('--deck-demo');
const answer = demo ? demoAnswer : 'Ready';
const demoDetail = (n) => ({ id:'PR_'+n, title:inbox.reviewRequested.find(p=>p.number===n).title, body:n===14 ? 'Moves `sessions` to its own table so history search can index Codex and Claude transcripts side by side.\n\n- Flyway migration `V12__sessions.sql`\n- Repository query for the sidebar\n- Backfill script for existing rows' : 'Refreshes the access token five minutes before expiry instead of on the first failed request.\n\nFixes APP-42.', state:'OPEN', isDraft:false, url:'https://example.test/'+n, author:'teammate', viewer:'me', baseRefName:'main', headRefName:n===14 ? 'feat/sessions-table' : 'fix/login-expiry', headRefOid:'a1b2c3d', additions:n===14 ? 142 : 38, deletions:n===14 ? 61 : 12, reviewDecision:null, mergeable:'MERGEABLE', mergeStateStatus:'BLOCKED', checks:[{name:'typecheck',state:'SUCCESS',url:null},{name:'test',state:'SUCCESS',url:null},{name:'lint',state:'SUCCESS',url:null}], mergeMethods:['squash'], reviewers:[{login:'me',state:'PENDING'}], autoMerge:null, commits:[{oid:'a1b2c3d',headline:n===14 ? 'add sessions table migration' : 'refresh token before expiry',author:'teammate',date:new Date(Date.now()-7200e3).toISOString()}], linkedIssues:n===14 ? [] : [{number:42,title:'Fix login expiry',url:'https://example.test/APP-42'}], files:n===14 ? [{path:'migrations/V12__sessions.sql',additions:24,deletions:0,viewed:false},{path:'src/sessions/repository.ts',additions:118,deletions:61,viewed:false}] : [{path:'src/auth/token.ts',additions:38,deletions:12,viewed:false}] });
const demoDiff = `diff --git a/src/auth/token.ts b/src/auth/token.ts\n--- a/src/auth/token.ts\n+++ b/src/auth/token.ts\n@@ -12,9 +12,14 @@ export class TokenStore {\n   async get(): Promise<string> {\n-    if (!this.token) await this.refresh();\n+    if (!this.token || this.expiresSoon()) await this.refresh();\n     return this.token;\n   }\n \n+  private expiresSoon(): boolean {\n+    return this.expiresAt - Date.now() < FIVE_MINUTES;\n+  }\n+\n   private async refresh(): Promise<void> {\n     const next = await this.client.refresh();\n     this.token = next.token;\n+    this.expiresAt = next.expiresAt;\n   }\n }\n`;
const fullscreen = [];
const terminalInputs = [];
const inbox = { viewer:'me', at:Date.now(), mine:[pr(12,{checks:'FAILURE',title:'Retry uploads on timeout'}), pr(13,{title:'Add dark theme'})], reviewRequested:[pr(14,{author:'teammate',title:'Migrate sessions table',updatedAt:new Date(Date.now()-3600e3).toISOString()}), pr(15,{author:'teammate',title:'APP-42 Fix login expiry'}), pr(16,{author:'teammate',title:'Draft idea',isDraft:true})] };
let next = 3;
const terms = [
 { id:'1', cwd:'/Users/demo/www/deck', agent:'codex', sessionId:'codex:demo', command:'codex' },
 { id:'2', cwd:'/Users/demo/www/api', agent:'claude', sessionId:'claude-demo', command:'claude' },
 { id:'3', cwd:'/Users/demo/www/deck' }
];
const sessions = [
 { session_id:'codex:demo', agent:'codex', cwd:terms[0].cwd, title:'Build a better terminal', status:'working', term_id:'1', issue_key:null, started_at:Date.now()-60000, updated_at:Date.now() },
 { session_id:'claude-demo', agent:'claude', cwd:terms[1].cwd, title:'Review authentication changes', status:'needs_review', term_id:'2', issue_key:'API-42', review_note:'Review the updated session expiry behavior.', started_at:Date.now()-60000, updated_at:Date.now() }
];
ipcRenderer.on('test:sessions', (_event, next) => { sessions.splice(0, sessions.length, ...next); callbacks.sessions.forEach(callback => callback(sessions)); });
const off = (kind,cb) => { callbacks[kind].push(cb); return () => callbacks[kind].splice(callbacks[kind].indexOf(cb),1); };
let zoom = 0;
let remembered = [];
const settings = {workspaces:[{id:'default',name:'Default',reviewSource:'github',board:{provider:'jira',rejectedPattern:'reject',doneWindowDays:7,reviewColumns:[],onMerge:{enabled:false,column:'',mode:'local'}},jira:{baseUrl:'',email:'',apiToken:'',boardId:''},linear:{apiKey:'',teamKey:''},githubProjects:{owner:'',projectNumber:''},github:{owner:'',repos:[]},repoRoots:[],defaultCwd:'~',layers:[{id:'main',name:'Main'}],activeLayer:'main',groups:[]}],activeWorkspace:'default',theme:'dark',keybinds:{},showTips:true,onboarded:true,terminalAppearance:{fontFamily:'',fontSize:13,fontWeight:'normal',fontWeightBold:'bold',lineHeight:1,cursorBlink:true,cursorStyle:'block'},defaultAgent:'codex',askModel:'sonnet',defaultView:'terminal',autoFix:{enabled:true,ci:true,conflicts:true,push:'review'},reviewSource:'github',defaultCwd:'~',newTerminalCwd:{tab:'current',split:'current'},repoRoots:[],windowMode:'shared',summonHotkey:'Alt+Space',summonHotkeyEnabled:true,summonDockToTop:true,summonHeightRatio:0.6,summonHideOnBlur:true,hideFromDock:false,board:{provider:'jira',rejectedPattern:'reject',doneWindowDays:7,reviewColumns:[],onMerge:{enabled:false,column:'',mode:'local'}},jira:{baseUrl:'',email:'',apiToken:'',boardId:''},linear:{apiKey:'',teamKey:''},githubProjects:{owner:'',projectNumber:''},agentSharing:{mode:'all',projects:[],transcripts:true,board:true,pullRequests:true},github:{owner:'',repos:[]},experiments:{sessionSweep:true},layers:[{id:'main',name:'Main'}],activeLayer:'main',groups:[]};
contextBridge.exposeInMainWorld('deck', {
 reviewedEvents:()=>reviewed, terminalInputs:()=>terminalInputs, removedWorktrees:()=>removedWorktrees, window:{focus:()=>ipcRenderer.invoke('test:focus-window'),onFocused:cb=>off('windowFocused',cb),setFullScreen:async(on)=>{fullscreen.push(on)},isFullScreen:async()=>false,zoomLevel:()=>zoom,setZoomLevel:(level)=>{zoom=level}}, fullscreenCalls:()=>fullscreen,
 canvas:{get:async(id)=>canvasFrames[id]??[],clear:async(id)=>{canvasFrames[id]=[];callbacks.canvas.forEach(cb=>cb(id,[]));return []},remove:async(id,frameId)=>{canvasFrames[id]=(canvasFrames[id]??[]).filter(f=>f.id!==frameId);callbacks.canvas.forEach(cb=>cb(id,canvasFrames[id]));return canvasFrames[id]},toggleTask:async(id,frameId,line)=>{canvasFrames[id]=(canvasFrames[id]??[]).map(f=>{if(f.id!==frameId)return f;const lines=f.content.split('\n');lines[line-1]=lines[line-1].replace(/\[( |x)\]/,(m,c)=>c===' '?'[x]':'[ ]');return {...f,content:lines.join('\n'),updatedAt:Date.now()}});callbacks.canvas.forEach(cb=>cb(id,canvasFrames[id]));return canvasFrames[id]},onChanged:cb=>off('canvas',cb)},
 hotkey:{registered:async()=>settings.summonHotkey,onSummoned:cb=>off('hotkeySummoned',cb)}, pressHotkey:()=>callbacks.hotkeySummoned.forEach(cb=>cb()),
 getSettings:async()=>settings, updateSettings:async(patch)=>{Object.assign(settings,patch);callbacks.settings.forEach(cb=>cb(settings));return settings},onSettingsChanged:cb=>off('settings',cb), onMenuCommand:cb=>off('menu',cb),
 extensions:{get:()=>ipcRenderer.invoke('test:catalog'),onChanged:cb=>off('extensions',cb),saveTheme:value=>ipcRenderer.invoke('test:save-theme',value),enablePlugin:(_path,enabled)=>ipcRenderer.invoke('test:enable',enabled),installPlugin:async()=>null,importTheme:async()=>null,openFolder:async()=>{}},
 term:{list:async()=>terms,create:async(opts)=>{const meta={...opts,id:String(++next),cwd:opts.cwd||'/Users/demo/www/deck'};terms.push(meta);callbacks.created.forEach(cb=>cb(meta));return meta},onCreated:cb=>off('created',cb),onExit:cb=>off('exit',cb),onCwd:cb=>off('cwd',cb),onBusy:cb=>off('busy',cb),onData:cb=>off('data',cb),attach:async(id)=> ({sequence:0,buffer:id==='1'? '\x1b[1mCodex\x1b[0m\r\n\r\n  /Users/demo/www/deck\r\n\r\n› Make Deck my everyday terminal.\r\n\r\n• Codex and Claude now share session tracking, history search,\r\n  and pull request review tools.\r\n\r\n• Running checks…\r\n\r\n\x1b[32m✓\x1b[0m TypeScript checks passed\r\n\x1b[32m✓\x1b[0m Session and transcript tests passed\r\n\r\n› ': '\x1b[32m~/www/deck\x1b[0m \x1b[90mgit:(main)\x1b[0m\r\n❯ '}), resize:()=>{},input:(id,data)=>terminalInputs.push({id,data}),pathForFile:file=>'/tmp/'+file.name,kill:id=>{terms.splice(terms.findIndex(t=>t.id===id),1);callbacks.exit.forEach(cb=>cb(id))},place:(id,placement)=>{const term=terms.find(t=>t.id===id);if(!term)return;if(placement.layer!==undefined)term.layer=placement.layer;if(placement.group!==undefined)term.group=placement.group??undefined},remembered:async()=>remembered,remember:tabs=>{remembered=tabs}},
 sessions:{list:async()=>sessions,onChanged:cb=>off('sessions',cb),hooksInstalled:async()=>true,installHooks:async()=>({installed:true,path:'/tmp/mock'}),remove:async()=>{},pullRequests:async(id)=>sessionPrs[id]??[]},
 project:{runtime:async()=>({label:'node',version:'v24.18.0'}),versions:async()=>({manager:'nvm',versions:['v24.18.0','v22.20.0']})},
 git:{summary:async(cwd)=>({branch:'main',added:529,removed:331,changedFiles:cwd.includes('/clean')?0:27}),changes:async()=>({diff:''}),branches:async()=>['main','INI-1234-context-bar']},
 sharing:{summary:async()=>({shared:2,total:3}),setCurrentProject:async()=>{}},
 worktrees:{at:async(cwd)=>worktrees.find(w=>cwd.startsWith(w.path))??null,list:async()=>worktrees,remove:async(target,deleteBranch)=>{const i=worktrees.findIndex(w=>w.path===target);if(i<0)return{removed:false,error:'not a linked worktree'};removedWorktrees.push({path:target,deleteBranch});worktrees.splice(i,1);return{removed:true}}},
 search:{query:async()=>[{session_id:'codex:history',agent:'codex',cwd:'/Users/demo/www/deck',title:'Codex conversation',project:'deck',snippet:'Found ⟪terminal⟫',last_at:Date.now()},...(demo?[{session_id:'claude:history-1',agent:'claude',cwd:'/Users/demo/www/api',title:'Why does the terminal lose scrollback after resize',project:'api',snippet:'xterm keeps the buffer but the fit addon resets rows when the ⟪terminal⟫ is hidden',last_at:Date.now()-2*86400e3},{session_id:'codex:history-2',agent:'codex',cwd:'/Users/demo/www/deck',title:'Add find in terminal with ⌘F',project:'deck',snippet:'Wired the search addon and a small overlay above the ⟪terminal⟫ pane',last_at:Date.now()-6*86400e3},{session_id:'claude:history-3',agent:'claude',cwd:'/Users/demo/www/api',title:'Flaky terminal smoke test on CI',project:'api',snippet:'The PTY exits before the ⟪terminal⟫ replays the buffer; wait for the first data event',last_at:Date.now()-12*86400e3}]:[])],session:async()=>demo?[{role:'user',text:'Why does the terminal lose scrollback after a resize?'},{role:'assistant',text:'The buffer is intact. The fit addon recomputes rows while the pane is hidden and xterm trims to the new row count. Defer fit until the pane is visible.'},{role:'user',text:'Fix it and add a regression test.'}]:[{role:'user',text:'A saved Codex conversation'}],listRepos:async()=>[],github:async()=>[],progress:async()=>({done:true,total:10,scanned:10}),onProgress:()=>()=>{}},
 files:{list:async()=>[{name:'src',path:'src',directory:true},{name:'package.json',path:'package.json',directory:false},{name:'README.md',path:'README.md',directory:false}],read:async()=>({text:'# Deck\n\nYour terminal, your agents.',modified:1}),save:async(root,file,contents)=>contents},
 board:{get:async()=>boardCache,sync:async()=>boardCache,move:async()=>boardCache,columns:async()=>[{name:'Plan',statuses:[{id:'1',name:'To Do'}]},{name:'Review',statuses:[{id:'2',name:'In Review'},{id:'3',name:'Rejected'}]}],onChanged:()=>()=>{}},ask:{onEvent:cb=>off('ask',cb),reset:async()=>{},send:async()=>{callbacks.ask.forEach(cb=>cb({type:'tool',name:'pr_inbox',input:'{}'}));return {ok:true,text:answer}}},
 inbox:{get:async()=>inbox,refresh:async()=>inbox,onChanged:()=>()=>{}},review:{send:async()=>({ok:true,text:answer}),reset:async()=>{},onEvent:()=>()=>{},drafts:async()=>[],addDraft:async()=>[],removeDraft:async()=>[],clearDrafts:async()=>[],onDrafts:()=>()=>{}},gh:{prDetail:async(_r,n)=>demo?demoDetail(n):null,prDiff:async()=>demo?demoDiff:'diff unavailable',prStack:async()=>({below:[],above:[]}),prComments:async()=>[],prTimeline:async()=>demo?[{kind:'opened',actor:'teammate',date:new Date(Date.now()-7200e3).toISOString(),detail:''},{kind:'commits',actor:'teammate',date:new Date(Date.now()-5400e3).toISOString(),detail:'1'},{kind:'review_requested',actor:'teammate',date:new Date(Date.now()-3600e3).toISOString(),detail:'me'}]:[],review:async(_r,_n,event)=>{reviewed.push(event);return {ok:true}}}
});
