const { app, BrowserWindow, ipcMain } = require('electron');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const output = path.join(root, 'artifacts/ui');
fs.mkdirSync(output, { recursive: true });
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'deck-ui-'));
app.setPath('userData', profile);
app.whenReady().then(async () => {
  const themeBundle = path.join(profile, 'themes.cjs');
  require('esbuild').buildSync({ entryPoints: [path.join(root, 'src/shared/themes.ts')], outfile: themeBundle, bundle: true, platform: 'node', format: 'cjs' });
  const { builtInThemes, parseTheme } = require(themeBundle);
  const pluginRoot = path.join(root, 'examples/plugins/workspace-kit');
  const manifest = JSON.parse(fs.readFileSync(path.join(pluginRoot, 'deck-plugin.json'), 'utf8'));
  const pluginTheme = { ...parseTheme(JSON.parse(fs.readFileSync(path.join(pluginRoot, 'ocean.json'), 'utf8'))), id: 'workspace-kit:ocean', source: manifest.name };
  const plugin = { ...manifest, path: pluginRoot, enabled: true, source: fs.readFileSync(path.join(pluginRoot, 'index.js'), 'utf8'), themes: [pluginTheme] };
  const customThemes = [];
  ipcMain.handle('test:catalog', () => ({ themes: [...builtInThemes, ...customThemes, ...(plugin.enabled ? [pluginTheme] : [])], plugins: [{ ...plugin, source: plugin.enabled ? plugin.source : undefined, themes: plugin.enabled ? plugin.themes : [] }], errors: [], themesDirectory: profile, pluginsDirectory: profile }));
  ipcMain.handle('test:enable', (_event, enabled) => { plugin.enabled = enabled; });
  ipcMain.handle('test:save-theme', (_event, input) => { const theme = { ...parseTheme(input), id: 'custom:' + input.id, source: 'Custom' }; customThemes.push(theme); return theme; });
  const window = new BrowserWindow({ width: 1440, height: 900, show: false, webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true }, backgroundColor: '#080808' });
  let focusRequests = 0;
  ipcMain.handle('test:focus-window', () => { focusRequests++; });
  const errors = [];
  window.webContents.on('console-message', (event) => { if (event.level === 'error') errors.push(event.message); });
  await window.loadFile(path.join(root, 'out/renderer/index.html'));
  const run = (script) => window.webContents.executeJavaScript(script);
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
  const screenshot = async (name) => { await wait(200); fs.writeFileSync(path.join(output, name + '.png'), (await window.webContents.capturePage()).toPNG()); };
  const click = async (label) => {
    const found = await run(`(() => { const button = [...document.querySelectorAll('button,[role=button]')].find(button => button.getAttribute('aria-label') === ${JSON.stringify(label)} || button.title === ${JSON.stringify(label)} || button.textContent.trim() === ${JSON.stringify(label)}); if (!button) return false; button.click(); return true; })()`);
    if (!found) throw Error('Missing control: ' + label);
    await wait(150);
  };
  const visiblePanes = () => run(`[...document.querySelectorAll('.xterm')].filter(element => element.offsetWidth > 0).length`);
  const chord = (init) => run(`window.dispatchEvent(new KeyboardEvent('keydown', {bubbles:true,cancelable:true,${init}}))`);
  const splitFromWidth = () => run(`Math.round(window.splitFrom.getBoundingClientRect().width)`);
  await wait(800);
  await click('Build a better terminal (Codex)');
  await screenshot('normal');
  await click('Change git branch');
  await click('INI-1234-context-bar');
  const checkout = await run(`window.deck.terminalInputs().at(-1)`);
  if (checkout.data !== 'git checkout INI-1234-context-bar\r') throw Error('Branch chip did not check out the branch in the shell');
  await click('Split right');
  if (await visiblePanes() !== 2) throw Error('Split did not show two panes');
  await screenshot('split');
  await run(`(() => {
    const panes = [...document.querySelectorAll('.xterm')].filter(element => element.offsetWidth > 0);
    window.dropTarget = panes.find(pane => !pane.contains(document.activeElement));
    const transfer = new DataTransfer();
    transfer.items.add(new File(['image'], 'focus test.png', {type:'image/png'}));
    window.dropTarget.dispatchEvent(new DragEvent('drop', {bubbles:true,cancelable:true,dataTransfer:transfer}));
    // Simulate focus being lost as the native drag ends.
    document.activeElement.blur();
  })()`);
  await wait(200);
  if (focusRequests !== 1) throw Error('File drop did not request window focus');
  if (!(await run(`window.dropTarget.contains(document.activeElement)`))) throw Error('File drop did not restore focus to the receiving pane');
  await run(`window.dispatchEvent(new Event('focus'))`);
  if (!(await run(`window.dropTarget.contains(document.activeElement)`))) throw Error('File drop did not select the receiving split pane');
  const pasted = await run(`window.deck.terminalInputs().at(-1)`);
  if (pasted.data !== "\x1b[200~'/tmp/focus test.png' \x1b[201~") throw Error('File drop changed the pasted image path');
  await run(`document.activeElement.dispatchEvent(new KeyboardEvent('keydown', {key:'x',code:'KeyX',keyCode:88,which:88,bubbles:true,cancelable:true}))`);
  const typed = await run(`window.deck.terminalInputs().at(-1)`);
  if (typed.id !== pasted.id || typed.data !== 'x') throw Error('Typing after a file drop did not reach the receiving terminal');
  if (process.argv.includes('--terminal-drop-only')) {
    if (errors.length) throw Error(errors.join('\n'));
    console.log('Terminal drop passed: window focus requested, receiving split selected, image path pasted, typing resumed.');
    window.destroy();
    app.quit();
    return;
  }
  await click('File explorer');
  if (!(await run(`document.body.innerText.includes('package.json')`))) throw Error('File explorer failed');
  await screenshot('files');
  await click('Close file explorer');
  await click('Zen view');
  if (!(await run(`document.querySelector('[data-display-mode="zen"]') && document.querySelector('aside').offsetWidth === 0`))) throw Error('Zen did not hide chrome');
  if (await visiblePanes() !== 1) throw Error('Zen should focus one pane');
  await screenshot('zen');
  await click('Exit zen view');
  if (await visiblePanes() !== 2) throw Error('Leaving Zen did not restore split');

  // WezTerm-style panes: ⌘⇧ and an arrow splits that way (up and left putting
  // the new pane first), ⌃⌘ moves focus, ⌘Z zooms and releases.
  await run(`window.splitFrom = [...document.querySelectorAll('.xterm')].find(element => element.offsetWidth > 0 && element.contains(document.activeElement))`);
  await chord(`key:'ArrowLeft',code:'ArrowLeft',metaKey:true,shiftKey:true`);
  await wait(500);
  if (await visiblePanes() !== 3) throw Error('⌘⇧← did not open a third pane');
  const placement = await run(`(() => {
    const target = window.splitFrom.getBoundingClientRect();
    const focused = [...document.querySelectorAll('.xterm')].find(element => element.offsetWidth > 0 && element.contains(document.activeElement));
    if (!focused) return 'focus left the panes';
    if (focused === window.splitFrom) return 'focus stayed on the pane it split from';
    const box = focused.getBoundingClientRect();
    if (box.left >= target.left) return 'the new pane is not left of the pane it split from';
    if (Math.abs(box.top - target.top) > 2) return 'a left split moved the pane to another row';
    return 'ok';
  })()`);
  if (placement !== 'ok') throw Error('⌘⇧←: ' + placement);
  await screenshot('split-left');
  await chord(`key:'ArrowRight',code:'ArrowRight',metaKey:true,ctrlKey:true`);
  await wait(200);
  if (!(await run(`window.splitFrom.contains(document.activeElement)`))) throw Error('⌃⌘→ did not move focus to the pane on the right');
  if (!(await run(`[...document.querySelectorAll('.xterm')].filter(element => element.offsetWidth > 0 && !element.contains(document.activeElement)).every(element => Boolean(element.closest('.terminal-pane-inactive')))`))) throw Error('Unfocused panes are not dimmed');
  const plainWidth = await splitFromWidth();
  await chord(`key:'z',code:'KeyZ',metaKey:true`);
  await wait(250);
  if (await splitFromWidth() <= plainWidth) throw Error('⌘Z did not grow the focused pane');
  await screenshot('split-zoom');
  await chord(`key:'z',code:'KeyZ',metaKey:true`);
  await wait(250);
  if (Math.abs(await splitFromWidth() - plainWidth) > 2) throw Error('⌘Z again did not restore the pane width');

  await click('Build a better terminal (Codex)');
  await click('Presentation view');
  if (await visiblePanes() !== 1) throw Error('Presentation should focus one pane');
  await screenshot('presentation');
  await click('Larger presentation text');
  if (!(await run(`document.body.innerText.includes('22px')`))) throw Error('Presentation font control failed');
  await click('Next presentation session');
  await click('Previous presentation session');
  await run(`window.dispatchEvent(new KeyboardEvent('keydown', {key:'Escape',bubbles:true,cancelable:true}))`);
  await wait(150);
  if (!(await run(`document.querySelector('[data-display-mode="normal"]')`))) throw Error('Escape did not exit presentation');
  await click('Toggle sidebar');
  if (await run(`Boolean(document.querySelector('aside[aria-label="Sessions"]'))`)) throw Error('Sidebar did not collapse');
  await click('Toggle sidebar');
  await click('New session');
  await click('New Codex');
  if (!(await run(`document.body.innerText.includes('Codex')`))) throw Error('Codex launch absent');
  await click('Settings');
  await screenshot('themes');
  await click('Use Paper theme');
  if (await run(`document.documentElement.dataset.theme`) !== 'light') throw Error('Theme did not apply');
  await click('terminal');
  await screenshot('light');
  await click('Settings');
  await click('Customize');
  await run(`(() => { const input = document.querySelector('textarea[aria-label="Custom theme JSON"]'); const setter = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value').set; setter.call(input, JSON.stringify({id:'ui-custom',name:'UI Custom',extends:'forest',colors:{accent:'#abcd12'}})); input.dispatchEvent(new Event('input',{bubbles:true})); })()`);
  await click('Preview');
  if (await run(`document.documentElement.dataset.theme`) !== 'ui-custom') throw Error('Custom theme preview failed');
  await click('Save theme');
  if (await run(`document.documentElement.dataset.theme`) !== 'custom:ui-custom') throw Error('Custom theme save failed');
  await click('Plugins');
  await click('Workspace overview');
  if (!(await run(`document.body.innerText.includes('Stay in flow')`))) throw Error('Worker plugin panel failed');
  await screenshot('plugin-panel');
  await click('Close plugin panel');
  await click('Switch to Ocean');
  if (await run(`document.documentElement.dataset.theme`) !== 'workspace-kit:ocean') throw Error('Plugin theme command failed');
  await screenshot('plugins');
  await run(`document.querySelector('input[aria-label="Enable Workspace Kit"]').click()`);
  await wait(200);
  if (await run(`[...document.querySelectorAll('button')].some(button => button.textContent.includes('Workspace overview'))`)) throw Error('Disabled plugin retained commands');
  await run(`document.querySelector('input[aria-label="Enable Workspace Kit"]').click()`);
  await wait(400);
  await click('Review workspace with Codex');
  if (!(await run(`document.body.innerText.includes('Codex')`))) throw Error('Plugin Codex launch failed');
  await click('Settings');
  await click('General');
  await wait(200);
  if (!(await run(`document.body.innerText.includes('Auto-fix my pull requests')`))) throw Error('General settings did not render');
  await screenshot('general-settings');
  await click('Workspaces');
  await wait(200);
  if (!(await run(`document.body.innerText.includes('Rejected status')`))) throw Error('Workspace settings did not render');
  await click('Appearance');
  await click('Use Carbon theme');
  await click('terminal');
  await run(`window.dispatchEvent(new KeyboardEvent('keydown', {key:'k',metaKey:true,bubbles:true,cancelable:true}))`);
  await wait(150);
  await run(`(() => { const input = document.querySelector('input[aria-label="Search Deck"]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'terminal'); input.dispatchEvent(new Event('input',{bubbles:true})); })()`);
  await wait(500);
  await click('Codex conversation');
  if (!(await run(`document.body.innerText.includes('A saved Codex conversation')`))) throw Error('Codex history preview failed');
  await screenshot('history');
  await click('Resume in terminal →');
  const resumed = await run(`window.deck.term.list()`);
  if (!resumed.some(term => term.agent === 'codex' && term.sessionId === 'codex:history')) throw Error('Codex history resume failed');
  await require('./sidebar.cjs')({ window, run, click, wait, screenshot });
  await click('agent');
  const rail = () => run(`document.querySelector('section[aria-label="Agent rail"]').innerText`);
  if (!(await rail()).includes('NEEDS YOU') || !(await rail()).includes('Review authentication changes')) throw Error('Agent rail did not list the session waiting on me');
  if (!(await rail()).includes('SESSIONS') || !(await rail()).includes('Build a better terminal')) throw Error('Agent rail did not list the running sessions');
  if (!(await run(`document.querySelector('aside').innerText`)).includes('2')) throw Error('Sidebar agent badge missing');
  const canvas = await run('document.body.innerText');
  if (!/Good (morning|afternoon|evening)\./.test(canvas) || !canvas.includes('Needs you:')) throw Error('The agent page did not lead with what is waiting');
  await screenshot('agent');
  await click('My PRs needing attention');
  if (!(await run(`[...document.querySelectorAll('.md')].some(element => element.innerText.includes('Ready'))`))) throw Error('Agent page did not render its completed answer');
  if (!(await run(`document.querySelector('[aria-label="Deck tools used"]').innerText`)).includes('pr_inbox')) throw Error('Agent page did not show the tool it used');
  await screenshot('agent-answer');
  await click('New chat');
  if (!(await run(`document.body.innerText.includes('Get started with some examples')`))) throw Error('New chat did not reset the agent page');
  await click('terminal');
  await click('Open agent');
  const dock = () => run(`document.querySelector('section[aria-label="Agent dock"]')?.innerText ?? ''`);
  if (!(await dock()).includes('Get started with some examples')) throw Error('Agent dock did not open from the terminal page');
  await click('PRs to review');
  await new Promise((resolve) => setTimeout(resolve, 300));
  if (!(await dock()).includes('Ready')) throw Error('Agent dock did not answer');
  await screenshot('agent-dock');
  await click('Close agent dock');
  await click('agent');
  if (!(await run(`[...document.querySelectorAll('.md')].some(element => element.innerText.includes('Ready'))`))) throw Error('Agent page lost the conversation started in the dock');
  await click('New chat');
  await click('reviews');
  const header = () => run(`document.body.innerText`);
  if (!(await header()).includes('1 of 2') || !(await header()).includes('Migrate sessions table')) throw Error('Review queue did not start with the oldest non-draft request');
  await screenshot('reviews');
  await click('Next review');
  if (!(await header()).includes('2 of 2') || !(await header()).includes('APP-42 Fix login expiry')) throw Error('Next did not advance the review queue');
  await click('Previous review');
  await click('Approve');
  await wait(1200);
  if (JSON.stringify(await run('window.deck.reviewedEvents()')) !== '["APPROVE"]') throw Error('Approve did not submit a review');
  if (!(await header()).includes('2 of 2') || !(await header()).includes('APP-42 Fix login expiry')) throw Error('Approving did not move to the next review');
  await run(`window.dispatchEvent(new KeyboardEvent('keydown', {key:'Enter',metaKey:true,shiftKey:true,bubbles:true,cancelable:true}))`);
  await wait(200);
  if (!(await run(`document.querySelector('[data-display-mode="zen"]') && document.querySelector('aside').offsetWidth === 0 && document.body.innerText.includes('APP-42 Fix login expiry') && document.body.innerText.includes('Reviews')`))) throw Error('Zen did not keep the reviews page while hiding chrome');
  if ((await run('window.deck.fullscreenCalls().at(-1)')) !== true) throw Error('Zen did not enter fullscreen');
  await screenshot('zen-reviews');
  await run(`window.dispatchEvent(new KeyboardEvent('keydown', {key:'Escape',bubbles:true,cancelable:true}))`);
  await wait(150);
  if (!(await run(`document.querySelector('[data-display-mode="zen"]')`))) throw Error('Escape outside the terminal should not exit Zen');
  await run(`window.dispatchEvent(new KeyboardEvent('keydown', {key:'p',metaKey:true,shiftKey:true,bubbles:true,cancelable:true}))`);
  await wait(200);
  if (await run(`Boolean(document.querySelector('input[aria-label="Search Deck"]'))`)) throw Error('⌘⇧P must not open search');
  if (!(await run(`document.querySelector('[data-display-mode="presentation"]') && getComputedStyle(document.querySelector('main > div:not(.hidden)')).zoom !== '1'`))) throw Error('Presentation did not zoom the reviews page');
  await screenshot('presentation-reviews');
  await click('Exit presentation view');
  if ((await run('window.deck.fullscreenCalls().at(-1)')) !== false) throw Error('Leaving the mode did not restore the window');
  if (errors.length) throw Error(errors.join('\n'));
  console.log('UI smoke passed: focus, splits, directional splits, pane focus, pane zoom and dimming, files, Zen, Presentation, font sizing, session navigation, Escape, sidebar, Codex launch, themes, custom preview/save, plugin worker panel, plugin themes, disable/enable agent command, Codex history preview and resume, recent suggestions, expiry, dismissal, search and close all, agent page greeting and rail, answer, tool trace and reset, agent dock sharing the conversation, review queue navigation and approve-then-next, Zen and Presentation on the reviews page.');
  window.destroy();
  app.quit();
}).catch((error) => { console.error(error); app.exit(1); });
setTimeout(() => { console.error('UI smoke timed out'); app.exit(1); }, 45000).unref();
